#include "gen-robot.pb.hpp"
#include "rpc/def.hpp"

RPCDEF_CPP((barobo, Robot),
        // all methods
        (getAccelerometerData)
        (getAdcRaw)
        (getLedColor)
        (setLedColor)
        (getBuzzerFrequency)
        (setBuzzerFrequency)
        (enableAccelerometerEvent)
        (enableButtonEvent)
        (enableEncoderEvent)
        (enableJointEvent)
        (getMotorControllerSafetyThreshold)
        (getMotorControllerSafetyAngle)
        (getMotorControllerAlphaI)
        (getMotorControllerAlphaF)
        (getMotorControllerOmega)
        (getMotorControllerProportionalGain)
        (getMotorControllerIntegratorGain)
        (getMotorControllerDerivativeGain)
        (setMotorControllerSafetyThreshold)
        (setMotorControllerSafetyAngle)
        (setMotorControllerAlphaI)
        (setMotorControllerAlphaF)
        (setMotorControllerOmega)
        (setMotorControllerProportionalGain)
        (setMotorControllerIntegratorGain)
        (setMotorControllerDerivativeGain)
        (setResetOnDisconnect)
        (getBatteryVoltage)
        (getEncoderValues)
        (getFormFactor)
        (getJointStates)
        (getButtonState)
        (getFirmwareVersion)
        (getFirmwareVersionString)
        (move)
        (resetEncoderRevs)
        (stop)
        (writeEeprom)
        (readEeprom)
        (writeTwi)
        (readTwi)
        (writeReadTwi)
        (reboot)
        (getBCRemotes)
        (getBCMaster)
        (getBCPoses)
        ,
        // all broadcasts
        (buttonEvent)
        (encoderEvent)
        (accelerometerEvent)
        (jointEvent)
        (debugMessageEvent)
        (connectionTerminated)
        )
